server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost:8081
    appname: user-service
