server:
  port: 8000
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8001/
          predicates:
            - Path=/users/**
